name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          check-latest: true

      - name: Unit Test
        env:
          DEFAULT_REGION: ap-northeast-1
          AWS_ACCOUNT_ID: "000000000000"
          AWS_ACCESS_KEY_ID: dummy-access-key
          AWS_SECRET_ACCESS_KEY: dummy-secret-key
        run: |
          yarn --frozen-lockfile
          docker-compose -f fake-service.yml up -d
          yarn unit-test
