name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Unit Test
        run: |
          docker-compose fake-service.yml up -d
          yarn unit-test
