name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          check-latest: true

      - name: Unit Test
        run: |
          yarn --frozen-lockfile
          docker-compose fake-service.yml up -d
          yarn unit-test
